apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-deployment
spec:
  template:
    spec:
      containers:
      - name: wordpress
        resources:
          requests:
            memory: "64Mi"
            cpu: "10m"
          limits:
            memory: "256Mi"
            cpu: "500m"
